services:
  centralshop:
    image: centralshop
    build:
      context: .
      dockerfile: CentralShop/Dockerfile
    depends_on:
      - centralshop_db
  
  centralshop_db:
    image: postgress
    
  officeshop:
    image: officeshop
    build:
      context: .
      dockerfile: OfficeShop/Dockerfile

