services:
  centralshop:
    image: centralshop
    build:
      context: .
      dockerfile: CentralShop/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      centralshop.db:
        condition: service_healthy
  
  centralshop.db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - csdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  officeshop:
    image: officeshop
    build:
      context: .
      dockerfile: OfficeShop/Dockerfile

  
volumes:
  csdb:
    